[package]
name = "serial_rs"
version = "0.1.0"
authors = ["Yasuhiro Yamada <yamada@gr3.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
chrono = "0.4.19"
